#insertJobDetailSql = "CALL add_job_detail(%s, 1, 6, 1, 0.00, %s, %s, 1, %s)"
insertJobDetailSql = "INSERT IGNORE INTO job_detail (restaurant_id, create_time, pickup_time_requested) VALUES (%s, %s, %s);"
allRestaurantIds = "SELECT id FROM restaurant"
setAutocommit = "SET autocommit=%s"
setUniqueChecks = "SET unique_checks=%s"
setForeignKeyChecks = "SET foreign_key_checks=%s"
